from gym_oscillator.envs.osc_env import oscillatorEnv
from gym_oscillator.envs.osc_env_rec import oscillatorEnv_Rec
from gym_oscillator.envs.osc_env_balance import oscillatorEnv_Bal
from gym_oscillator.envs.osc_env_discrete import oscillatorEnv_dis
